# Generated by Django 3.0.5 on 2020-04-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=64)),
                ('birthday', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
