# Generated by Django 3.0.5 on 2020-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='blog',
            name='phone',
            field=models.CharField(max_length=64),
        ),
    ]
